// sfera-client/src/app/connection-page/connection-page.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { SignalingService } from '../signaling/signaling.service';
@Component({
  selector: 'app-connection-page',
  templateUrl: './connection-page.component.html',
  styleUrls: ['./connection-page.component.scss']
})
export class ConnectionPageComponent {
  serverAddress = ""
  serverPort = 4000
  remember = false
  constructor(
    private router: Router,
    private signalingService: SignalingService
  ) {}

  async tryConnect() {
    await this.signalingService.connect(this.serverAddress, this.serverPort, this.remember)
    this.router.navigate(["/peers"])
  }
}

<div class="page">
    <mat-card class="connection-page-header">
        <img src="../../assets/sfera.png" height="120" width="120">
    </mat-card> 
    <div class="column inner-padding-md">
        <mat-form-field class="full-width">
            <mat-label>Server Address</mat-label>
            <input
                [(ngModel)]="serverAddress"
                matInput
                placeholder="e.g. 192.168.20.20"
            />
        </mat-form-field>
    
        <mat-form-field class="full-width">
            <mat-label>Server Port</mat-label>
            <input
                [(ngModel)]="serverPort"
                matInput
                placeholder="4000"
            />
        </mat-form-field>
    
        <mat-checkbox color="primary" [(ngModel)]="remember">
            Don't ask me again
        </mat-checkbox>
        <div class="row justify-center">
            <button 
                mat-raised-button
                style="width: 200px; color: white;"
                color="primary"
                (click)="tryConnect()"
            >
                Connect
            </button> 
        </div>   
    </div>
</div>

// sfera-client/src/pages/ConnectionPage.vue
<template>
  <div
    class="column"
    style="height: 100vh;"
  >
    <div
      class="column justify-center items-center q-pa-md bg-primary"
      style="height: 30vh"
    >
      <span class="text-h5 text-weight-bold">Sfera</span>
    </div>
    <q-card
      class="q-px-xs column justify-center items-center q-gutter-y-sm"
      style="flex:1"
    >
      <q-input
        v-model="ipAddress"
        label="Server Address"
        filled
      />
      <q-input
        v-model="port"
        label="Server Port"
        filled
      />
      <div
        class="row justify-begin"
        style="width: 215px;"
      >
        <q-checkbox
          v-model="remember"
          label="Don't ask me again"
        />
      </div>
      <q-btn
        label="Connect!"
        color="primary"
        icon="mdi-connection"
        class="q-mt-md"
        @click="tryConnect()"
      />
    </q-card>
  </div>
</template>

<script setup lang="ts">
import useSferaConnection from "src/composables/useSferaConnection"
import { ref } from "vue"
import { useRouter } from "vue-router"

const ipAddress = ref("")
const port = ref("")
const remember = ref(false)

const { connect } = useSferaConnection()
const router = useRouter()
const tryConnect = () => {
  connect(ipAddress.value, Number(port.value), remember.value)
  router.push("/peers")
}
</script>
